### PR TITLE
chore: upgrade dependencies to the latest version

### PR DESCRIPTION
**Pull request by dsueltenfuss**
Implements the following changes
* Upgrades dependency packages to the latest versions
* Upgrades minimum node version to 12

### CODE REVIEW

**Comment by roccomuso** [comment]
as this package has no unit test, did you test it?

**Comment by dsueltenfuss** [comment]
Yes, I am running the fork on my project currently, and have not encountered any issues

**Comment by roccomuso** [comment]
did you run also the `standard` linter?

**Comment by dsueltenfuss** [comment]
Yes, it completed without error

**Pull request merged**
